# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=1000)),
                ('sub_phrase', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'SearchPhrase',
                'db_table': '',
                'managed': True,
                'verbose_name_plural': 'SearchPhrases',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=1000)),
                ('search_phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_set', to='api.SearchPhrase')),
            ],
            options={
                'verbose_name': 'Tweet',
                'db_table': '',
                'managed': True,
                'verbose_name_plural': 'Tweets',
            },
        ),
    ]
