# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchphrase',
            name='sub_phrase',
        ),
    ]
