# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190423_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchphrase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
