# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_searchphrase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchphrase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
